name: fcarreno
favicon: null
layout_spectrum: 0.51465
typography_spectrum: 0.50366
title: Francisco Carreño
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcdcd'
    - '#000000'
    - '#999999'
    - '#524f48'
    - '#281d23'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
